"""
Avatar provenance records.

Every avatar asset ships with a record of where the face came from. This is not
bureaucracy — it is the difference between an asset you can sell a product with
and one you cannot:

  - a generated face needs the generating model's licence (FLUX.1-schnell is
    Apache-2.0; FLUX.1-dev is not, and the distinction is invisible in the PNG),
  - a photographed or filmed face needs recorded consent from the person, and
    for a synthetic likeness of a real person you need that in writing,
  - either way you need a hash, so the audit can prove the file that shipped is
    the file that was cleared.

`assets/nova.png` in the original repo is exactly the failure this prevents: an
AI-generated portrait with cropped UI chrome still in frame, no model recorded,
no licence, no hash. Unshippable, and nothing in the file says so.
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import asdict, dataclass, field

SCHEMA = 1


class ProvenanceError(ValueError):
    pass


@dataclass
class Provenance:
    """Where an avatar asset came from and whether it can be sold."""
    asset: str                       # path, relative to the bundle
    kind: str                        # portrait | driving_video
    origin: str                      # generated | photographed | filmed | derived
    sha256: str = ""
    # generated assets
    model: str | None = None
    model_licence: str | None = None
    prompt: str | None = None
    seed: int | None = None
    # real-person assets
    subject: str | None = None
    consent_reference: str | None = None   # contract / release form ID
    # derived assets record what they came from
    derived_from: str | None = None
    created_at: float = field(default_factory=time.time)
    schema: int = SCHEMA

    def validate(self) -> "Provenance":
        """Raise unless this record is sufficient to clear commercial use."""
        from ..providers.licences import commercial_ok, is_noncommercial

        if self.origin == "generated":
            if not self.model:
                raise ProvenanceError(f"{self.asset}: generated asset needs `model`")
            if is_noncommercial(self.model_licence):
                raise ProvenanceError(
                    f"{self.asset}: generated by {self.model} whose licence "
                    f"'{self.model_licence}' forbids commercial use")
            if not commercial_ok(self.model_licence):
                raise ProvenanceError(
                    f"{self.asset}: model licence '{self.model_licence}' is not on "
                    f"the approved list — record the real licence before shipping")
        elif self.origin in ("photographed", "filmed"):
            if not self.subject or not self.consent_reference:
                raise ProvenanceError(
                    f"{self.asset}: a real person's likeness needs both `subject` "
                    f"and `consent_reference` (a signed release you can produce)")
        elif self.origin == "derived":
            if not self.derived_from:
                raise ProvenanceError(f"{self.asset}: derived asset needs `derived_from`")
        else:
            raise ProvenanceError(f"{self.asset}: unknown origin {self.origin!r}")

        if not self.sha256:
            raise ProvenanceError(f"{self.asset}: sha256 not recorded")
        return self


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def write_manifest(bundle_dir: str, records: list[Provenance]) -> str:
    """Write bundle.json describing every asset. Validates first, so an
    unshippable bundle never gets a manifest that claims otherwise."""
    for r in records:
        r.validate()
    path = os.path.join(bundle_dir, "bundle.json")
    with open(path, "w") as f:
        json.dump({"schema": SCHEMA, "created_at": time.time(),
                   "assets": [asdict(r) for r in records]}, f, indent=2)
    return path


def read_manifest(bundle_dir: str) -> list[Provenance]:
    path = os.path.join(bundle_dir, "bundle.json")
    if not os.path.exists(path):
        raise ProvenanceError(f"no bundle.json in {bundle_dir}")
    with open(path) as f:
        data = json.load(f)
    return [Provenance(**a) for a in data.get("assets", [])]


def verify_bundle(bundle_dir: str) -> list[str]:
    """Re-hash every asset and confirm it matches what was cleared.

    Returns a list of problems; empty means the bundle on disk is exactly the
    bundle that passed validation.
    """
    problems: list[str] = []
    try:
        records = read_manifest(bundle_dir)
    except ProvenanceError as e:
        return [str(e)]
    for r in records:
        path = os.path.join(bundle_dir, r.asset)
        if not os.path.exists(path):
            problems.append(f"{r.asset}: listed in manifest but missing on disk")
            continue
        actual = sha256_file(path)
        if actual != r.sha256:
            problems.append(f"{r.asset}: sha256 mismatch "
                            f"(manifest {r.sha256[:12]}…, disk {actual[:12]}…)")
        try:
            r.validate()
        except ProvenanceError as e:
            problems.append(str(e))
    return problems
