#!/usr/bin/env python3
"""Runs every engine's prove() for real and writes the actual captured
output to PROOFS.md. No engine is registered in ENGINE_CATALOGUE.md unless
its prove() actually ran here and passed -- this script IS the evidence
generator, not a summary of claims.

Usage: python run_all_proofs.py
"""
import importlib
import json
import os
import sys
import traceback

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

ENGINES = [
    "audit_trail", "stage_history", "stage_conditional_requiredness", "record_cloning",
    "scheduling_availability", "scheduled_jobs", "stock_ledger", "ledger_balancing",
    "search_fts", "import_export", "file_conversion", "email_parsing",
    "bank_feed_ofx", "calendar_ics", "document_signing", "document_generation",
    "pdf_form_filling",
]


def main():
    results = {}
    failures = []
    for name in ENGINES:
        mod = importlib.import_module(name)
        try:
            results[name] = mod.prove()
            print(f"[PASS] {name}")
        except Exception as e:
            failures.append((name, traceback.format_exc()))
            print(f"[FAIL] {name}: {e}")

    lines = ["# Engine proofs -- actual captured output\n",
             "Generated by `run_all_proofs.py`. Every entry below is the real "
             "return value of that engine's own `prove()`, run against a real "
             "system, just now -- not a hand-written claim.\n"]
    for name in ENGINES:
        if name not in results:
            continue
        r = results[name]
        lines.append(f"\n## {name}\n")
        lines.append(f"**Real system**: {r['real_system']}\n")
        lines.append("**Steps**:")
        for s in r["steps"]:
            lines.append(f"- {s}")
        lines.append(f"\n**Observed** (actual captured output):\n```json\n{json.dumps(r['observed'], indent=2, default=str)}\n```\n")

    with open(os.path.join(HERE, "..", "PROOFS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n{len(results)}/{len(ENGINES)} engines proven; wrote PROOFS.md")
    if failures:
        print(f"{len(failures)} FAILURES:")
        for name, tb in failures:
            print(f"--- {name} ---\n{tb}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
