#!/usr/bin/env python3
"""
lock_structure.py — freezes a template's numbered build structure, once, ever.

The five templates in templates/*.json are answer-sets: a template only holds
answers to question_graph_v3.json, never a structure of its own. Assembling
used to mean recomputing "structure" (which screen exists, which action, its
number) fresh from those answers on every run, via the Assembly Engine's
derive()/build_model() (packages/assembly-engine/assemble.py). Nothing was
permanent: run it twice with the answers reordered and the numbers could land
differently.

This script runs that same derive()/build_model() (imported, not
reimplemented -- there is exactly one place in this repo that turns answers
into a build model) and writes the result back into the template file as a
new top-level "structure" key -- EXACTLY ONCE. If a template already carries
a "structure" block, this script refuses to touch it: it does not recompute,
does not re-derive, does not renumber, does not even read the answers again.
It prints that the template is already locked and returns the existing
structure completely unchanged. There is no flag to force a relock -- a
locked structure cannot be re-derived or regenerated by any later step,
including a later run of this same script.

Every id in a locked structure (SCR-nnn, ACT-nnn, REC-nnn, NOTIF-nnn,
RPT-nnn, STG-nnn, TRN-nnn, OPS-nnn, QA-nnn) is prefixed with the template's
own name ("pm-teamwork/SCR-001"), so combining templates later can never
collide two numbers.

The answers/per_instance themselves are untouched -- they remain the one real
record of which question produced which value, still validated the normal
way by check_template.py. This is not a second requirements system: it is a
frozen build artifact of the one that already exists.

Usage:
  python lock_structure.py templates/<name>.json [more...]
  python lock_structure.py --all
"""

import copy
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ASSEMBLY_DIR = os.path.join(HERE, "..", "assembly-engine")
sys.path.insert(0, os.path.abspath(ASSEMBLY_DIR))
sys.path.insert(0, HERE)

import assemble as ae          # noqa: E402  (derive()/build_model() -- reused, not reimplemented)
import check_template          # noqa: E402  (the real, non-parallel validator -- must PASS first)
import graph_lib               # noqa: E402

GRAPH_PATH = os.path.join(HERE, "question_graph_v3.json")
TEMPLATE_DIR = os.path.join(HERE, "templates")


def lock_one(graph, path):
    """Returns (structure, already_locked). Writes the file only the first
    time a template is locked; every call after that is a pure no-op read."""
    t = json.load(open(path, encoding="utf-8"))
    name = t["template"]

    if t.get("structure"):
        bm = t["structure"]
        if "interface" not in bm:
            # A wholly new numbered kind, added after this template was
            # already locked. This is deliberately NOT a relock: nothing
            # else in bm is touched, re-derived, or renumbered -- the
            # existing invariant (an id, once minted, never moves) holds.
            # Minting exactly one IFC-001 the first time this key is absent
            # is additive, not a recomputation, so it's safe to do on an
            # already-locked template.
            bm["interface"] = {"id": f"{name}/IFC-001", "kind": "interface",
                                "options": ["console", "board", "pocket"], "chosen": None}
            json.dump(t, open(path, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
        return bm, True

    errors = check_template.check(graph, t)
    if errors:
        raise SystemExit(f"{name}: refuses to lock a template that fails check_template.py:\n" +
                          "\n".join(f"  - {e}" for e in errors))

    derived = ae.derive(graph, t)
    # build_model()'s nested dicts/lists (e.g. a workflow's "transitions")
    # are the SAME objects as t["per_instance"]'s own raw answer data --
    # ae.derive()'s D08 hands them back by reference, not by copy. Mutating
    # bm in place below (minting ids, prefixing them) would silently corrupt
    # the real per_instance answers with structure-only fields unless this
    # is a fully independent copy first -- a real bug this exact check
    # caught (a "reproduce byte-for-byte" test failing because ids leaked
    # into per_instance).
    bm = copy.deepcopy(ae.build_model(t, derived))
    n = {"SCR": 0, "ACT": 0, "REC": 0, "NOTIF": 0, "RPT": 0, "STG": 0, "TRN": 0, "OPS": 0, "QA": 0}

    def mint(kind):
        n[kind] += 1
        return f"{kind}-{n[kind]:03d}"

    # every record gets a permanent number, alongside its already-present fields
    for rec_name in t["inventory"]["records"]:
        bm["records"][rec_name]["id"] = mint("REC")

    old_id_by_scr_old_id = {}
    for scr in bm["screens_inventory"]:
        old_id_by_scr_old_id[scr["id"]] = mint("SCR")
    for scr in bm["screens_inventory"]:
        scr["id"] = old_id_by_scr_old_id[scr["id"]]
    bm["navigation"] = [s["id"] for s in bm["screens_inventory"]]

    old_act_id_map = {}
    for act in bm["actions_inventory"]:
        old_act_id_map[act["id"]] = mint("ACT")
    for act in bm["actions_inventory"]:
        act["id"] = old_act_id_map[act["id"]]

    for op in bm["recurring_ops"]:
        op["id"] = mint("OPS")

    # qa_generated_tests reference an action by "action_id" (and embed the full
    # action under "action") and a screen by "screen_id" -- rewrite both to the
    # freshly assigned ids before numbering the tests themselves.
    for qa in bm["qa_generated_tests"]:
        if qa.get("action_id") in old_act_id_map:
            qa["action_id"] = old_act_id_map[qa["action_id"]]
            qa["action"] = next(a for a in bm["actions_inventory"] if a["id"] == qa["action_id"])
        if qa.get("screen_id") in old_id_by_scr_old_id:
            qa["screen_id"] = old_id_by_scr_old_id[qa["screen_id"]]
    for qa in bm["qa_generated_tests"]:
        qa["id"] = mint("QA")

    for notif in bm["notifications"].values():
        notif["id"] = mint("NOTIF")
    for rep in bm["reports"].values():
        rep["id"] = mint("RPT")
    for w in bm["workflows"].values():
        stages = w.get("stages") or {}
        stage_names = stages.get("stages") if isinstance(stages, dict) else (stages or [])
        w["stages"] = [{"id": mint("STG"), "name": s} for s in (stage_names or [])]
        w["initial"] = (stages.get("initial") if isinstance(stages, dict) else None)
        w["terminal"] = (stages.get("terminal") if isinstance(stages, dict) else None)
        for tr in w.get("transitions") or []:
            tr["id"] = mint("TRN")

    # prefix every id with the template name, so combining templates can never
    # collide two numbers.
    def prefixed(x):
        return f"{name}/{x}"

    for rec in bm["records"].values():
        rec["id"] = prefixed(rec["id"])
    for scr in bm["screens_inventory"]:
        scr["id"] = prefixed(scr["id"])
    bm["navigation"] = [prefixed(s) for s in bm["navigation"]]
    for act in bm["actions_inventory"]:
        act["id"] = prefixed(act["id"])
    for op in bm["recurring_ops"]:
        op["id"] = prefixed(op["id"])
    for qa in bm["qa_generated_tests"]:
        qa["id"] = prefixed(qa["id"])
        if qa.get("action_id"):
            qa["action_id"] = prefixed(qa["action_id"])
            qa["action"] = dict(qa["action"], id=qa["action_id"])
        if qa.get("screen_id"):
            qa["screen_id"] = prefixed(qa["screen_id"])
    for notif in bm["notifications"].values():
        notif["id"] = prefixed(notif["id"])
    for rep in bm["reports"].values():
        rep["id"] = prefixed(rep["id"])
    for w in bm["workflows"].values():
        for st in w["stages"]:
            st["id"] = prefixed(st["id"])
        for tr in w.get("transitions") or []:
            tr["id"] = prefixed(tr["id"])

    bm["locked"] = True
    bm["locked_at_graph_version"] = graph["version"]
    t["structure"] = bm
    json.dump(t, open(path, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    return bm, False


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if not argv:
        print(__doc__)
        return 2
    graph = graph_lib.load_graph(GRAPH_PATH)
    paths = sorted(glob.glob(os.path.join(TEMPLATE_DIR, "*.json"))) if argv[0] == "--all" else argv
    for p in paths:
        bm, already = lock_one(graph, p)
        status = "already locked (unchanged)" if already else "locked"
        print(f"{os.path.basename(p)}: {status} -- {len(bm['records'])} records, {len(bm['screens_inventory'])} screens, "
              f"{len(bm['actions_inventory'])} actions, {len(bm['notifications'])} notifications, "
              f"{len(bm['reports'])} reports, {len(bm['workflows'])} workflows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
